### ISSUE TITLE
Run PhpArrayConverter on all PHP files extensions on save

### ISSUE THREAD

**Issue by madeindjs** [gh640/SublimePhpArrayConverter#3]
The `pre_save` event does not work for  these extensions 

* _*.phtml_
* _*.php5_
*  _*.php_

**Comment by gh640** [comment]
Thank you for sharing the issue.

It may be caused as the syntax of your file is different from the supported one. Currently only `PHP.sublime-syntax` is supported.

What is displayed if you type `sublime.active_window().active_view().settings().get('syntax')` in the Sublime Text console when you show `*.phtml`, `*.php5` or `*.php`?

**Comment by madeindjs** [comment]
You had right, it was a different syntax. Thank you for your help :)

**Comment by gh640** [comment]
Thank you, too :)
